spring:

  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test_master
          username: dev
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/test_slaver
          username: dev
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/test_master?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  #    username: dev
  #    password: 123456
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
